
services:

  db:
    image: postgres:18-alpine
    container_name: nextjs-captcha-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: research_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ตั้งชื่อ Service
  backend-api:
    # บอกว่าให้ Build จาก Dockerfile ที่อยู่ในโฟลเดอร์ backend
    build: ./backend
    # ตั้งชื่อ Container
    container_name: go-captcha-backend
    # Map Port 8080:8080
    ports:
      - "8080:8080"
    # Hot Reload
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=research_db
      - DB_PORT=5432
      - PORT=8080


  frontend:
    build: ./frontend
    
    container_name: nextjs-captcha-frontend

    ports:
      - "3000:3000"
    
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

    environment:
      - WATCHPACK_POLLING=true
    
    depends_on:
      - backend-api

volumes:
  postgres_data:
    