
services:
  # ตั้งชื่อ Service
  backend-api:
    # บอกว่าให้ Build จาก Dockerfile ที่อยู่ในโฟลเดอร์ backend
    build: ./backend
    # ตั้งชื่อ Container
    container_name: go-captcha-backend
    # Map Port 8080:8080
    ports:
      - "8080:8080"
    # Hot Reload
    volumes:
      - ./backend:/app

    environment:
      - PORT=8080
  frontend:
    build: ./frontend
    
    container_name: nextjs-captcha-frontend

    ports:
      - "3000:3000"
    
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

    environment:
      - WATCHPACK_POLLING=true
    
    depends_on:
      - backend-api

    